### ISSUE TITLE
pip install doesnt work with python 3.4, windows x64

### ISSUE THREAD

**Issue by isaacgerg** [jakebian/quiver#10]
`c:\Python34\Scripts>pip install quiver_engine
Collecting quiver_engine
  Downloading quiver_engine-0.1.4.1.1.tar.gz (398kB)
    100% |################################| 399kB 1.4MB/s
Requirement already satisfied: keras in c:\python34 (from quiver_engine)
Collecting flask (from quiver_engine)
  Downloading Flask-0.11.1-py2.py3-none-any.whl (80kB)
    100% |################################| 81kB 2.6MB/s
Collecting flask_cors (from quiver_engine)
  Downloading Flask_Cors-3.0.2-py2.py3-none-any.whl
Collecting gevent (from quiver_engine)
  Downloading gevent-1.1.2-cp34-cp34m-win_amd64.whl (384kB)
    100% |################################| 389kB 1.5MB/s
Requirement already satisfied: numpy in c:\python34\lib\site-packages (from quiver_engine)
Requirement already satisfied: pillow in c:\python34\lib\site-packages (from quiver_engine)
Requirement already satisfied: theano in c:\python34\lib\site-packages (from keras->quiver_engine)
Requirement already satisfied: pyyaml in c:\python34\lib\site-packages (from keras->quiver_engine)
Requirement already satisfied: six in c:\python34\lib\site-packages (from keras->quiver_engine)
Collecting itsdangerous>=0.21 (from flask->quiver_engine)
  Downloading itsdangerous-0.24.tar.gz (46kB)
    100% |################################| 51kB 4.3MB/s
Collecting Werkzeug>=0.7 (from flask->quiver_engine)
  Downloading Werkzeug-0.11.11-py2.py3-none-any.whl (306kB)
    100% |################################| 307kB 2.1MB/s
Collecting click>=2.0 (from flask->quiver_engine)
  Downloading click-6.6.tar.gz (283kB)
    100% |################################| 286kB 2.8MB/s
Collecting Jinja2>=2.4 (from flask->quiver_engine)
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
    100% |################################| 266kB 3.1MB/s
Collecting greenlet>=0.4.9 (from gevent->quiver_engine)
  Downloading greenlet-0.4.10-cp34-cp34m-win_amd64.whl
Requirement already satisfied: scipy>=0.11 in c:\python34\lib\site-packages (from theano->keras->quiver_engine)
Collecting MarkupSafe (from Jinja2>=2.4->flask->quiver_engine)
  Downloading MarkupSafe-0.23.tar.gz
Installing collected packages: itsdangerous, Werkzeug, click, MarkupSafe, Jinja2, flask, flask-cors, greenlet, gevent, quiver-engine
  Running setup.py install for itsdangerous ... done
  Running setup.py install for click ... done
  Running setup.py install for MarkupSafe ... done
  Running setup.py install for quiver-engine ... error
    Complete output from command c:\python34\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\idg101\\AppData\\Local\\Temp\\pip-buil
d-8ffm_h7y\\quiver-engine\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __fi
le__, 'exec'))" install --record C:\Users\idg101\AppData\Local\Temp\pip-2amt2zih-record\install-record.txt --single-version-externally-managed --compi
le:
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\quiver_engine
    copying quiver_engine\imagenet_utils.py -> build\lib\quiver_engine
    copying quiver_engine\layer_result_generators.py -> build\lib\quiver_engine
    copying quiver_engine\server.py -> build\lib\quiver_engine
    copying quiver_engine\util.py -> build\lib\quiver_engine
    copying quiver_engine\__init__.py -> build\lib\quiver_engine
    running egg_info
    writing quiver_engine.egg-info\PKG-INFO
    writing dependency_links to quiver_engine.egg-info\dependency_links.txt
    writing requirements to quiver_engine.egg-info\requires.txt
    writing top-level names to quiver_engine.egg-info\top_level.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'quiver_engine.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'quiver_engine.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\idg101\AppData\Local\Temp\pip-build-8ffm_h7y\quiver-engine\setup.py", line 20, in <module>
        'pillow'
      File "c:\python34\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\python34\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\python34\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\python34\lib\distutils\command\install.py", line 539, in run
        self.run_command('build')
      File "c:\python34\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\python34\lib\distutils\command\build.py", line 126, in run
        self.run_command(cmd_name)
      File "c:\python34\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\python34\lib\site-packages\setuptools\command\build_py.py", line 47, in run
        self.build_package_data()
      File "c:\python34\lib\site-packages\setuptools\command\build_py.py", line 103, in build_package_data
        for package, src_dir, build_dir, filenames in self.data_files:
      File "c:\python34\lib\site-packages\setuptools\command\build_py.py", line 59, in __getattr__
        self.data_files = files = self._get_data_files()
      File "c:\python34\lib\site-packages\setuptools\command\build_py.py", line 86, in _get_data_files
        file[plen:] for file in self.find_data_files(package, src_dir)
      File "c:\python34\lib\site-packages\setuptools\command\build_py.py", line 94, in find_data_files
        + self.package_data.get(package, []))
    TypeError: can only concatenate list (not "str") to list

    ----------------------------------------
Command "c:\python34\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\idg101\\AppData\\Local\\Temp\\pip-build-8ffm_h7y\\quiver-engin
e\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install
--record C:\Users\idg101\AppData\Local\Temp\pip-2amt2zih-record\install-record.txt --single-version-externally-managed --compile" failed with error co
de 1 in C:\Users\idg101\AppData\Local\Temp\pip-build-8ffm_h7y\quiver-engine\
`

**Comment by jakebian** [comment]
Hmm I do not have easy access to a windows machine to test this at the moment, would love it if someone else can send a PR for this

**Comment by isaacgerg** [comment]
Can you point me to a tutorial on how files for pip are created?  I'd be happy to debug; I've never deployed with pip before.

**Comment by bubzebub** [comment]
I get a similar error with RHEL 6 and Python 2.7.

**Comment by ZFTurbo** [comment]
The same issue for me at windows10 + python3.4

**Comment by octycs** [comment]
Had the same problem with python 3.5 on Fedora 21.
It worked for me when I replaced `'quiverboard/dist/*'` with `['quiverboard/dist/*']` in *setup.py*, compiled the client and then installed with `python setup.py install`.

**Comment by chaosmail** [comment]
Same for me on Ubuntu 16.04 using Python 3.5.2.
Following @octycs advide and running `pip3 install -e .` did the trick.

**Comment by taichu012** [comment]
agree with upstair, detail desrcription:
1. search keyword "quiver“ at pypi webside (https://pypi.python.org/pypi);
2. download one of quiver package name "quiver_engine 0.1.4.1.4";
3. unzip it on local disk and "cd ..\..\quiver_engine 0.1.4.1.4\”;
4. just run "pip install -e .", it will auto call setup.py, then quiver_engine installed without any problem;
5. run python under dos "cmd";
6. just for test, type "from quiver_engine impor server" and no error is reported;
7. just for use in keras, look detail on function server.lunch, type "help(quiver_engine.server.lanuch", you will find it suggest only 5 parameter like below and NEEDN'T CLASSES MEAN STD TOP these 4 parameters!!!"
----------------
>>> help(server.launch)
Help on function launch in module quiver_engine.server:
launch(model, temp_folder='./tmp', input_folder='./', port=5000, html_base_dir=None)
------------------------
8. it you add codes below, you MUST first make dir you need first!
server.launch(model = model,temp_folder='./quiver/tmp',input_folder='./quiver/input_imgs',port=5000)
9, run codes with launch function in pycharm or python, quiver_engine will OPEN A WEBPAGE show your images (you FIRST copy to input_folder before run codes) and select it to see feature maps in your diagram show also on web page's left frame. 
10. if it run OK as mentioned in step 9, you trains will BLOCKED by quiver_engine!
