### ISSUE TITLE
/predict fails with 500

### ISSUE THREAD

**Issue by kretes** [jakebian/quiver#12]
When I am changing the input image in the GUI a call to /predict fails:

```
[2016-11-15 23:01:57,142] ERROR in app: Exception on /predict/20161112121702_52.16003_21.0718_1000006.jpg [GET]
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/lib/python2.7/site-packages/quiver_engine/server.py", line 104, in get_prediction
    model.predict(input_img)
  File "/opt/conda/lib/python2.7/site-packages/quiver_engine/imagenet_utils.py", line 40, in decode_predictions
    'Found array with shape: ' + str(preds.shape))
ValueError: `decode_predictions` expects a batch of predictions (i.e. a 2D array of shape (samples, 1000)). Found array with shape: (1, 1)
```

my model is a binary classification model - maybe that's why there is the 2nd '1' in the output shape

**Comment by kretes** [comment]
Ok I looked a bit deeper in the code and I can see it is currently tightly bound to imagenet classes.

I guess to make it work for a generic model one would need to provide a list of classes names to present in the GUI

**Comment by jakebian** [comment]
yeah the prediction decoding was more of a gimick for imagenet - the task here should be to support passing an arbitrary decoding dictionary - for now one can simply replace the decoding function in the source, but yes we definitely should support it.

**Comment by jakebian** [comment]
This is fixed by your PR @kretes!
