### ISSUE TITLE
No data for this layer

### ISSUE THREAD

**Issue by guozhizou** [jakebian/quiver#29]
Quiver start normally, model and images are all visiable, but when I clicked the Input Layer (or other layers), got an error:

Any ideas?
```
E tensorflow/core/client/tensor_c_api.cc:485] input_1:0 is both fed and fetched.
[2016-11-21 10:02:37,298] ERROR in app: Exception on /layer/input_1/ILSVRC2012_val_00000610.jpg [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nali/Workspace/quiver/quiver_engine/server.py", line 103, in get_layer_outputs
    layer_outputs = output_generator(input_img)[0]
  File "/usr/local/lib/python2.7/site-packages/keras/engine/training.py", line 1197, in predict
    batch_size=batch_size, verbose=verbose)
  File "/usr/local/lib/python2.7/site-packages/keras/engine/training.py", line 896, in _predict_loop
    batch_outs = f(ins_batch)
  File "/usr/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1040, in __call__
    updated = session.run(self.outputs + [self.updates_op], feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 382, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 655, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 723, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 743, in _do_call
    raise type(e)(node_def, op, message)
InvalidArgumentError: input_1:0 is both fed and fetched.
127.0.0.1 - - [2016-11-21 10:02:37] "GET /layer/input_1/ILSVRC2012_val_00000610.jpg HTTP/1.1" 500 444 0.065454
[2016-11-21 10:02:37,323] ERROR in app: Exception on /predict/ILSVRC2012_val_00000610.jpg [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nali/Workspace/quiver/quiver_engine/server.py", line 127, in get_prediction
    input_img = load_img(input_path, single_input_shape, grayscale=is_grayscale)
  File "/Users/nali/Workspace/quiver/quiver_engine/util.py", line 27, in load_img
    img = image.load_img(input_path, target_size=target_shape, grayscale=grayscale)
  File "/usr/local/lib/python2.7/site-packages/keras/preprocessing/image.py", line 173, in load_img
    img = Image.open(path)
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 2272, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: u'ILSVRC2012_val_00000610.jpg'
127.0.0.1 - - [2016-11-21 10:02:37] "GET /predict/ILSVRC2012_val_00000610.jpg HTTP/1.1" 500 444 0.006262
```

**Comment by jakebian** [comment]
Did you install with pip or clone the git repo?

**Comment by guozhizou** [comment]
I cloned the repo and builded from master yesterday.

**Comment by guozhizou** [comment]
Fixed after reinstalled.
