### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by guozhizou** [jakebian/quiver#30]
When I check each Layer to see what happens, got this error:

```
127.0.0.1 - - [2016-11-23 09:59:47] "GET /layer/predictions/ILSVRC2012_val_00020333.jpg HTTP/1.1" 500 444 1.400068
Warning! you didn't pass your own set of classes for the model therefore imagenet classes are used
127.0.0.1 - - [2016-11-23 09:59:49] "GET /predict/ILSVRC2012_val_00018548.jpg HTTP/1.1" 200 562 0.780195
[2016-11-23 09:59:50,946] ERROR in app: Exception on /layer/predictions/ILSVRC2012_val_00018548.jpg [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nali/Workspace/quiver/quiver_engine/server.py", line 112, in get_layer_outputs
    for z in range(0, layer_outputs.shape[2]):
IndexError: tuple index out of range
127.0.0.1 - - [2016-11-23 09:59:50] "GET /layer/predictions/ILSVRC2012_val_00018548.jpg HTTP/1.1" 500 444 1.402432
```

**Comment by Wanke15** [comment]
same problem +1
